[package]

name = "stm32f1"
version = "0.16.0"
edition = "2024"


[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.5"
cortex-m-semihosting = "0.5.0"
panic-halt = "1.0.0"
rtt-target = "0.6.1"

